"""empty message

Revision ID: e494be69b6fe
Revises: a5cffa318ac2
Create Date: 2025-06-08 13:30:49.553593

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e494be69b6fe'
down_revision = 'a5cffa318ac2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('username', sa.String(length=10), nullable=False))
        batch_op.add_column(sa.Column('photo_url', sa.String(), nullable=True))
        batch_op.add_column(sa.Column('first_name', sa.String(length=20), nullable=False))
        batch_op.add_column(sa.Column('las_name', sa.String(length=20), nullable=False))
        batch_op.add_column(sa.Column('date_of_birth', sa.Date(), nullable=False))
        batch_op.create_unique_constraint(None, ['photo_url'])
        batch_op.create_unique_constraint(None, ['username'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='unique')
        batch_op.drop_constraint(None, type_='unique')
        batch_op.drop_column('date_of_birth')
        batch_op.drop_column('las_name')
        batch_op.drop_column('first_name')
        batch_op.drop_column('photo_url')
        batch_op.drop_column('username')

    # ### end Alembic commands ###
